### ISSUE TITLE
Umschaltung auf "Klassische Ansicht" in App deaktivieren

### ISSUE THREAD

**Issue by mojoaxel** [fuerthwiki/wiki#68]
Wenn der Benutzer die WebApp installiert hat sollte die Möglichkeit zur Klassischen Ansicht zu wechseln deaktiviert werden.

**Comment by mojoaxel** [comment]
Fixed in [MediaWiki:Mobile.css](https://www.fuerthwiki.de/wiki/index.php/MediaWiki:Mobile.css):

```css
/**
 * Hide View-Switcher "Klassische Ansicht" if started from Homescreen.
 * fixes https://github.com/fuerthwiki/wiki/issues/68
 */
@media all and (display-mode: standalone) {
  #footer-info-mobile-switcher {
  	display: none;
  }
}
```
